#include "stm32f4xx_hal.h"
#include "dsp.h"
#include "bluetooth_handler.h"

/* State */
#define BT_CONNECTED 	0
#define BT_DISCONNECTED 1

/* Command */
#define CMDSIZE_BTYE    8
#define CMD_HELLO       0X01
#define CMD_EDITASTAGE  0X02
#define CMD_BYE         0X03

/*[TODO]ABOUTME should be autogenerated by objecy "dsp" rather than by human.*/
#define ABOUTME "{\"Name\":\"uRock-Lite0.1\", \"Stage Number\":2, \"Effects\": [ {\"Name\":\"None\", \"Attr\":[]} ,{\"Name\":\"Distortion0\", \"Attr\":[ [\"tone\",\"percent\",50,100,0], [\"gain\",\"x\",50,100,0]]} ,{\"Name\":\"Subsystem\", \"Attr\":[ [\"freq\",\"hz\",1500,4000,0], [\"depth\",\"percent\",100,50,0], [\"fs\",\"hz\",3000,10000,1000]]} ]}\n\r"

/*[HARDCODE]BIND WITH USART1 AND MYDSP BY DEFAULT*/
extern DSP mydsp;
extern UART_HandleTypeDef huart1;

uint8_t bt_result[CMDSIZE_BTYE];
int params[CMDSIZE_BTYE];
int bt_state;

int bluetooth_handler_init(){
	/*[Note]Triggered every 8 byte*/
	bt_state = BT_DISCONNECTED;
	HAL_UART_Receive_IT(&huart1, bt_result, CMDSIZE_BTYE);
	return 1;
}

/* A Bluetooth Handler trrigered by android controlling app. */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart){
	switch(bt_result[0]){
		case CMD_HELLO:
			//SENT ABOUT ME TO ANDROID TANSMIT_IT
			if(bt_state == BT_DISCONNECTED){
				bt_state = BT_CONNECTED;
				HAL_UART_Transmit_IT(&huart1, ABOUTME, strlen(ABOUTME));
			}
			break;
		case CMD_EDITASTAGE:
			//CHANGE EFFECT STAGE
			if(bt_state == BT_CONNECTED){
				int i;
				for(i=0;i<6;i++){
					params[i] = bt_result[i+3];
				}
				dsp_setStage(&mydsp, (int)bt_result[1], (int)bt_result[2],params);
				//HAL_UART_Transmit_IT(&huart1, &Txstr, strlen(Txstr))
			}
			break;
		case CMD_BYE:
			//BACK TO DISCONNECTED MODE
			if(bt_state == BT_CONNECTED){
				bt_state = BT_DISCONNECTED;
				//HAL_UART_Transmit_IT(&huart1, &Txstr, strlen(Txstr));
			}
			break;
		default:
			break;
	}
	/*DEBUG*/HAL_GPIO_TogglePin(GPIOG,GPIO_PIN_13);//data flow working well at 16 01 14 03 29(no effect) -> 5:08(no param) ->
	HAL_UART_Receive_IT(&huart1, bt_result, CMDSIZE_BTYE);
}
